### ISSUE TITLE
Repository / plug for data graph

### ISSUE THREAD

**Issue by stdimensiy** [stdimensiy/My_Readers_Diary_DA#59]
Необходимо переделать заглушку для графика данных
для этого нужно создать два метода
первый возвращает список объектов совокупной недельной активности, за определенный период (от текущей даты, до указанной в параметре) но с нулевыми значениями активности (так называемый чистый лист)
второй метод возвращает также список совокупной недельной активности за период (также передаваемый в параметре) но со значением активности заполненном в случайном порядке целым числом в диапазоне от 0 до 20
- старую заглушку после запуска и обкатки методов следует удалить из репозитория.

**Comment by azhukov2204** [comment]
Создал методы getRandomSummaryEventData and getClearSummaryEventData в Repository
Ссылка на PR:
https://github.com/stdimensiy/My_Readers_Diary_DA/pull/71

**Comment by azhukov2204** [comment]
С реализацией проекта ознакомился. Есть моменты, которые на мой взгляд можно улучшить:
1) Сущности в пакете domain я бы реорганизовал:
В domain создал бы только pojo-объекты (data-классы, модели данных без лишних зависимостей, таких как аннотации для retrofit).
Объекты, используемые для обмена с сервером вынес бы в слой данных и разбил бы на 2 типа: request и resnonse
Маппинг объектов request/resnonse в доменные объекты - в интеракторе.
Т.е. разделить ответственность.
Тогда конечно кода будет чуть побольше, зато улучшаются возможности по масштабируемости. И архитектура становится более чистой.
2) lateinit и !! в коде лучше не использовать (lateinit был введен для Dagger). Kotlin славится null safety, а использование lateinit и !! сводит на нет это преимущество. Над таким рефакторингом тоже можно будет поработать.
3) Во вью моделях репозитории стоит передавать через конструктор. Тогда будет проще внедрять DI и писать тесты. И лучше между вьюмоделью и репозиторием поставить интерактор.
4) Довольно часто встречаются "Магические значения" - их стоит вынести в константы.
5) При использовании LiveData я бы лучше вместо setValue использовал бы всегда postValue. setValue можно использовать только для передачи значения в текущем потоке, а postValue - потокобезопасный оператор, который можно использовать в любых случаях.
6) В CallBack.kt можно переписать определение интерфейса на вот такую строчку:
typealias CallBack<T> = (T) -> Unit
И тогда все коллбэки можно будет описывать в виде коротких lambda-выражений (без переопределения onResult(), а сразу в фигурных скобках реализация).
7) В объекте RetrofitClientDA свойство retrofit думаю стоит сделать приватным.
А в объекте Common для retrofitService думаю лучше сделать ленивую инициализацию (при переопределении get() для свойства каждый раз при обращении происходит пересчет значения и каждый раз вызывается create).
8) Если DI пока не используется, то думаю для создания экземпляров объектов репозиториев, интеракторов и т.п. использовать паттерн factory (как нам показывал преподаватель на курсе популярных библиотек).

Посмотрите, по вышеперечисленному задачи также можете на меня назначать. Но реализацией могу заниматься только по выходным.

**Comment by stdimensiy** [comment]
Спасибо! Все по делу. 
Напишите когда конкретно (даты когда вы будете свободны, ведь явно это будет не в Новый Год... хотя :-)
