### ISSUE TITLE
DEADME - актуализация информации

### ISSUE THREAD

**Issue by stdimensiy** [stdimensiy/My_Readers_Diary_DA#74]
Разместить новые скриншоты и видео

**Comment by DarthVerteliy** [comment]
Скриншоты свежие:
![Screenshot_20211227_133920_ru vdv myapp myreadersdiary](https://user-images.githubusercontent.com/84448182/147465994-544facd2-853e-4029-8821-0963db49a40c.jpg)
![Screenshot_20211227_133802_ru vdv myapp myreadersdiary](https://user-images.githubusercontent.com/84448182/147465995-8a409833-bf6a-4b45-be74-6df1695173d2.jpg)
![Screenshot_20211227_133817_ru vdv myapp myreadersdiary](https://user-images.githubusercontent.com/84448182/147465997-9785a88a-75d0-4eda-9558-f9d0240ed20b.jpg)
![Screenshot_20211227_133825_ru vdv myapp myreadersdiary](https://user-images.githubusercontent.com/84448182/147465998-88ac519b-597a-4922-b44b-7bd506dc93df.jpg)
![Screenshot_20211227_133905_ru vdv myapp myreadersdiary](https://user-images.githubusercontent.com/84448182/147465999-7498e86a-972d-4531-ac7b-55607f9bd59e.jpg)
