### ISSUE TITLE
UI Fragment Reading book using the Stopwatch

### ISSUE THREAD

**Issue by stdimensiy** [stdimensiy/My_Readers_Diary_DA#81]
Создать разметку и организовать работу фрагмента "контроль чтения"
в разметке создать интерфейс секундомера.
создать 3 кнопки управляющие процессом "приступить к чтению", "сделать паузу", "закончить сеанс чтения" 
нажатие на кнопку "временно приостановить" должно заменить ее название и внешний вид (значок) на "продолжить чтение"
нажатие на кнопку "приступить к чтению" должно запустить отсчет времени секундомером и одновременно вывести в текстовое поле сообщение что-то типа "закладка на такой то странице"
нажатие на кнопку сделать паузу должно остановить процесс фиксации времени основного процесса и запустить отсчет времени паузы (отображение должно отличаться  и на экране должны будут одновременно присутствовать и время основного процесса чтения (остановленное) (цвет белый например) и время паузы в чтении (например выводимое шрифтом поменьше и цветом например синим) которое будет идти.
По нажатии коноки паузы в режиме продолжения чтения, время паузы должно быть остановлено, вьюха с временем паузы должна быть погашена (пусть с небольшой задержкой)
по нажатии кнопки "закончить сеанс чтения" секундомер должен быть остановлен, также если не остановлен секундомер паузы должен быть остановлен он, должен быть выдан запрос на ввод номера текущей страницы, после ввода которой необходимо выполнить расчет и вывести пользователю результат "чтение заняло столько то времени, прочитано столько то страниц, средняя скорость чтения сегодня (в рамках сеанса) такая то.

**Comment by azhukov2204** [comment]
Дмитрий, приветствую!

Первая версия фрагмента контроля чтения готова.
При разработке фрагмента в первую очередь уделял внимание архитектуре: реализация в соответствии с MVVM с единым стейтом.
Для реализации единого стейта создал классы:
ScreenUiState – общий класс, для описания состояния экрана (Success, Error, Loading) – тут по аналогии, как мы делали на занятиях.
ProcessReadingBookUiModel – это UI-модель информации, отображаемой на экране фрагмента.

Фрагмент ProcessReadingBookFragment содержит только логику отображения информации (render). За формирование UI-модели информации отвечает ProcessReadingBookViewModel.
Также во вьюмодели использую SavedStateHandle – считаю применение SavedStateHandle хорошей практикой.
Логика секундомера в пакете model/stopwatch.
Также в своем коде добавил несколько комментариев – некоторые моменты (на мой взгляд) по улучшению логики/архитектуры проекта.

Для открытия фрагмента использовать такую навигацию:
.navigate(R.id.nav_process_reading_book_fragment, bundle)
В bundle поместить объект Book.

Замечание: логика работы секундомера реализована в начальном варианте. Для демонстрации работы текущая логика годится вполне . Но все-таки, для корректной работы секундомера следует реализовывать сервис (Service) и запускать его в режиме foreground.
(Android может выгружать из памяти свернутые приложения, если системе не хватает ресурсов – в этом случае работа секундомера прервется).
Создание такого сервиса тянет на отдельную задачу. Поэтому подумайте, какую следующую задачу по проекту на меня назначить. Как вариант – могу заняться реализацией сервиса для секундомера. Или заняться реализацией другого функционала.

Также оставлю несколько комментариев по результатам работы над проектом:
1)	Для вьюх, которые находятся внутри ConstraintLayout, не рекомендуется использовать значение match_parent для указания высоты или ширины . Более правильно указать 0dp и привязку к parent. Есть такая общая рекомендация для ConstraintLayout.
2)	В проекте следует придерживаться единых правил наименования объектов, переменных и т.п. Сейчас в проекте единого стандарта нет: fragment_list_of_books.xml, fragment_summary_statistics.xml, process_reading_book_fragment.xml, create_new_book_fragment.xml
3)	Для растровых  картинок в ресурсах приложения лучше использовать png (.png  - предпочтителен, .jpg  - приемлем, .gif  - нежелателен – есть такие общие рекомендации)
