### ISSUE TITLE
Фрагмент чтения книги

### ISSUE THREAD

**Issue by stdimensiy** [stdimensiy/My_Readers_Diary_DA#89]
Необходимо пересмотреть фрагмент еще раз.
Обратить внимание на то, что он  не переживает поворот экрана
Немного изменить дизайн, убрать счет миллисекунд (чтение спокойный процесс, нужно сделать это фрагмент менее динамичным) секунд будет достаточно.
От всей книги оставьте только наименование и текущую страницу.
Сделайте шрифт циферблата как минимум раза в 2 больше, постарайтесь поискать реализацию секундомера со стрелками и секторами, если это окажется сложно, тогда просто выберите шрифт похожий на цифры часов с электронным циферблатом (сегментные). В общем от всего фрагмента в части его информативности во время чтения должен остаться фактически только сам циферблат секундомера, на нем акцент. Над ним немного информации о книге которую читаем (наименование) и  текущая страница (например указываемая та " 21.01.2022  / Закладка на странице 45"
секундомер а под ним две кнопки с реализованным ранее функцилналом.
Прошу также добавить третью кнопку с функцией которая не останавливая время основного цикла чтения, меняет способ отображения. Не сколько человек уже читает а сколько ему осталось от запланированного (возбмем пока магическим числом и ограничим стандартный период непрерывного чтения 30 минутами) как только обратный отчет дойдет до 0 путь будет подан сигнал, но отсчет продолжается уже с пометкой, "сверх плана" столько то...
Действие функции изменения способа отображения должно быть обратимо. т. е. при повторном нажатии должен вернуться первый режим отображения. и так сколько угодно.
Еще прошу обратить внимание на диалог заключительный когда пользователь решил закончить читатьи ему предлагается ввести значение. Прошу реализовать возможность не вводя значение вернуться к чтению. и второе, при вызове данного диалога сразу активируйте чифровую клавиатуру и ограничьте вводимые значения только целыми числами, только положительными соответственно не менее 0 и не более общего количества страниц.  (вообще наверное интереснее вам будет реализовать дополнительную возможность быстро ввести значение страницы без использования клавиатуры (альтернативный способ) через ползунок.
Посмотрите пожалуйста.

**Comment by azhukov2204** [comment]
Задание реализовано, pull request оформлен
